### ISSUE TITLE
Image Loader Service 구성

### ISSUE THREAD

**Issue by SAgiKPJH** [SagiK-Repository/Learn_DDD#35]
# 진행 과정

## 기초
- [x] DockerHelloWorld - [docker 기반 hellow world 서비스 구성](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404492792)
- [x] DockerDIService - [docker 기반 di 서비스 구성](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404519472)
- [x] DockerGrpcServer - [docker 기반 grpc 서비스 구성](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404624046)
- [x] DockerGrpcClient - [docker 기반 grpc 서비스 2개간 통신 구성](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404758016)
- [x] DockerGrpcServer2 - [docker 기반 grpc 서비스 2개간 통신 구성 (서버 - 서버)](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2441465719)

## 서비스 구성
- [ ] [docker db 구성](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35)
- [ ] rabbitmq 구성
- [ ] redis 구성

## 서비스 구현
- [ ] 기능별 서비스 TDD로 구현
- [ ] client 구현

## 모니터링 구현
- [ ] log 서비스 모니터링 구현
- [ ] 서비스 자원 모니터링 구현
- [ ] grafana 구현

**Comment by SAgiKPJH** [comment]
# docker 기반 hellow world 서비스 구성
- 참고 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/31#issue-2258900933)
- 새프로젝트 -> C# 콘솔앱 -> 추가정보(아래 이미지 설정) -> 만들기
  - ![image](https://github.com/user-attachments/assets/cc001a5d-fa77-47c7-84a1-3bbcac6934df)
```cs
// Program.cs
Console.WriteLine("Hello, World!");
```
- 실행
  - ![image](https://github.com/user-attachments/assets/7150c056-3918-4c92-b63d-a97bf50a86d5)
  - ![image](https://github.com/user-attachments/assets/636eb422-3f3c-414e-8cc3-a139c03459bb)
  - ![image](https://github.com/user-attachments/assets/1a230340-2d90-40d4-9a85-29b2b6259714)
- Example
  - e4f456c181ad563e28b9e7b002ac758c2dddd796

**Comment by SAgiKPJH** [comment]
# docker 기반 di 서비스 구성

- 참고 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/20)
- DockerHelloWorld와 동일하게 구성 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404492792)
- Nuget Package 추가
  - Microsoft.Extensions.Hosting
- appsettings.json 추가
  - ![image](https://github.com/user-attachments/assets/e7d88b83-bf64-46f2-abe0-5878ed21aed2)
  - ```json
    {
    }
    ```
```cs
// Program.cs
using DockerDIService.PrintService;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var build = new ConfigurationBuilder();

build.SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
    .AddEnvironmentVariables();

var host = Host.CreateDefaultBuilder()
    .ConfigureServices((context, services) =>
    {
        services.AddTransient<IPrint, PrintConsole>();
    })
    .Build();

var printService = host.Services.GetRequiredService<IPrint>();
printService.Print("Hello World!");
```
```cs
public interface IPrint
{
    public void Print(string message);
}

public class PrintConsole : IPrint
{
    public void Print(string message) =>
        Console.WriteLine(message);
}
```
![image](https://github.com/user-attachments/assets/18aef8c3-e1c2-46b7-a71b-7df2af1ea0cf)

- Example
  - 9b10cbe095ca76b030bb999f560d3e6408270f80

**Comment by SAgiKPJH** [comment]
#  docker 기반 grpc 서비스 구성

- 참고 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/29)
- Protos
  - ![image](https://github.com/user-attachments/assets/37b84201-ef9e-45d3-932d-048ceac20d35)
  - ```protos
    syntax = "proto3";
    
    option csharp_namespace = "DockerGrpcServer.Protos";
    
    service Hello {
    	rpc Hello (HelloRequest) return (HelloReply);
    }
    
    message HelloRequest {
    	string message = 1;
    }
    
    message HelloReply {
    	string reply = 1;
    }
    ```
- 빌드 후 실행한 뒤 -> Hello Service 구성 가능
  - ![image](https://github.com/user-attachments/assets/1268282f-015b-449b-b81c-aedce570b683)
```cs
using DockerGrpcServer.Protos;
using Grpc.Core;

namespace DockerGrpcServer.Services;

public class HelloService : Hello.HelloBase
{
    public HelloService() { }

    public override async Task<HelloReply> Hello(HelloRequest request, ServerCallContext context)
    {
        await Task.CompletedTask;
        return new HelloReply() { Reply = "Hello World!" };
    }
}
```
```cs
using DockerGrpcServer.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddGrpc();

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapGrpcService<HelloService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
```
![image](https://github.com/user-attachments/assets/b64ec750-aa98-452b-bdaf-9920d01bf00f)
- grpc 수신 대기 상태입니다.


* Example
  * 35b68afb9348b1b70aa8caa84194b6164e2b8822

**Comment by SAgiKPJH** [comment]
# docker 기반 grpc 서비스 2개간 통신 구성

- 참고 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/29)
- Docker DI Service와 동일하게 구성 [링크](https://github.com/SagiK-Repository/Learn_CleanArchitecture/issues/35#issuecomment-2404519472)
- Add Nuget Package
  - Google.Protobuf
  - Grpc.Net.Client : grpc 서버와 통신
  - Grpc.Tools : Visual Studio 도구 사용하기 위함
- Server에서 Proto 파일 복사 -> Client에 붙여넣기 후 속성 -> Build Actiion : Protobuf Compiler, Stub Classas : Client Only 변경
  - ![image](https://github.com/user-attachments/assets/bfea92d7-63a5-4db1-b451-dbc7532e3331)
- 이후 빌드 및 실행 후 client 함수 작성

### Docker-Compose
- 여러 Docker를 연결시키기 위해 docker-compose 구현합니다.
- 서비스 > 추가 > 컨테이너 오케스트라
  - ![image](https://github.com/user-attachments/assets/a82f5e48-9384-4864-9739-05b36545df47)  
  - ![image](https://github.com/user-attachments/assets/eab951ae-a489-4128-9f92-7d845e297295)
  - ![image](https://github.com/user-attachments/assets/8fcc5e55-eb44-43e9-a03f-8ac0adecc416)

### 내부 외부 포트 설정 방법
- ![image](https://github.com/user-attachments/assets/24ac60cb-bf08-4264-a66e-2f1edd4dd5fe)
- launchSettings.json 파일에 명시되어 있습니다.
  - https의 포트에 해당하는 port를 연결합니다.
  - 하지만 docker에서 같은 네트워크간에 포트 설정은 필요하지 않습니다.
- 서비스 끼리 같은 네트워크 공간에 연결시킬 수 있습니다.
- server port
```json
# Server launchSettings.json의 https를 확인합니다.
# Local 연결의 경우
"applicationUrl": "https://localhost:63461;http://localhost:63462"
# Docker 연결의 경우
    "Container (Dockerfile)": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "environmentVariables": {
        "ASPNETCORE_HTTPS_PORTS": "8081",
        "ASPNETCORE_HTTP_PORTS": "8080"
      },
```
  - 여기서, client에서는 launchUri에 접근하면 됩니다.
    - ServiceHost는 Docker 실행의 이름 (docker-compose.yml에 명시되어 있습니다)
- client에서는 다음과 같이 연결합니다.
```json
# client appsettings.json
{
  "GrpcSettings": {
    "ServerUrl": "https://dockergrpcserver:63461"
  }
}
``` 

* Example
  * 80f3f1b07126e86377e50bc030bc8ec36ee4c7f0
<br/><br/><br/>

# [tip] 일반 프로젝트 도커화
- 프로젝트 도커화
  - 프로젝트 > 추가 > Docker 지원
  - ![image](https://github.com/user-attachments/assets/a6eef1b0-6b4a-42ca-a8b3-497b9fd1a9be)

**Comment by SAgiKPJH** [comment]
# docker 기반 grpc 서비스 2개간 통신 구성 (서버 - 서버)
 
![image](https://github.com/user-attachments/assets/4cb8dc9f-ac48-4c74-8e9a-922f098a6b6b)
- DockerGrpcServer2_1
  - ![image](https://github.com/user-attachments/assets/1bc42d4d-158c-4884-8150-ce333cae44fa)
- DockerGrpcServer2_2
  - ![image](https://github.com/user-attachments/assets/0e98187d-7801-4264-8e7b-65f434d359f1)
- Example
  - 73aaf04b5c0eb64c2ceb5c2b35853fdf0fbcd064

**Comment by SAgiKPJH** [comment]
# Docker db 구성

- 예제
  - ![image](https://github.com/user-attachments/assets/b72b117f-688f-4e79-9bb9-d7f695a18f23)
- 구성
  - ![image](https://github.com/user-attachments/assets/a3e10203-d6b0-491b-9499-ffa2d0cdcfbe)

## Docker Project 관리법

1. ClassLibrary 프로젝트 관리
   - ![image](https://github.com/user-attachments/assets/1449175d-0111-4cc8-ba38-bed816468edf)
   - 프로젝트 폴더에 Dockerfile이 존재하면 빌드시 프로잭트를 Docker 프로젝트로 인식하여 오류가 발생합니다.
     - 반드시 하위 폴더 또는 다른 이름의 이름으로 명명합니다.
   - docker-compose에서는 다음과 같이 dockerfile을 명시합니다.
```yml
services:
  dockerdb.platform.db.postgre:
    build: 
      dockerfile: Docker DB/DockerDB.Platform.DB/Postgre/Dockerfile # 파일 지정 방법
    build: Docker DB/DockerDB.Platform.DB/Postgre/ # 디렉토리 지정 방법
    ports:
      - "5432:5432"
```
2. 도커 이미지로 dockerfile 구성
   - dockerfile을 사전에 빌드하여 이미지를 만들고 docker hub에 등록을 한 뒤, 그 이름을 갖고 docker-compose에서 등록합니다.
3. docker-compose에서 명시
   - 별도의 dockerfile 없이 바로 docker-compose에서 구성합니다.
```yml
services:
  dockerdb.platform.db.postgre:
    image: postgres:latest
    environment:
      POSTGRES_DB: ImageHandlerServiceDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: @@@@@
    ports:
      - "5432:5432"
```

## Postgre DB 접근
- ![image](https://github.com/user-attachments/assets/8f2dcee1-e6c2-4401-bb83-3d2bc9ca83b3)
